class_name JsonInputProfileUtil

const MODIFIERS := PoolStringArray(["alt", "shift", "control", "meta", "command" ])
const KEY_FIELDS := PoolStringArray(["physical_scancode", "scancode", "unicode"])


# @todo remove in 4.0 :-)
# in 3.x you cannot access built-in enums as const dictionaries
enum JoyStickList {
	SONY_CIRCLE = JOY_SONY_CIRCLE
	SONY_X = JOY_SONY_X
	SONY_SQUARE = JOY_SONY_SQUARE
	SONY_TRIANGLE = JOY_SONY_TRIANGLE
	XBOX_B = JOY_XBOX_B
	XBOX_A = JOY_XBOX_A
	XBOX_X = JOY_XBOX_X
	XBOX_Y = JOY_XBOX_Y
	DS_A = JOY_DS_A
	DS_B = JOY_DS_B
	DS_X = JOY_DS_X
	DS_Y = JOY_DS_Y
	VR_GRIP = JOY_VR_GRIP
	VR_PAD = JOY_VR_PAD
	VR_TRIGGER = JOY_VR_TRIGGER
	OCULUS_AX = JOY_OCULUS_AX
	OCULUS_BY = JOY_OCULUS_BY
	OCULUS_MENU = JOY_OCULUS_MENU
	OPENVR_MENU = JOY_OPENVR_MENU
	SELECT = JOY_SELECT
	START = JOY_START
	DPAD_UP = JOY_DPAD_UP
	DPAD_DOWN = JOY_DPAD_DOWN
	DPAD_LEFT = JOY_DPAD_LEFT
	DPAD_RIGHT = JOY_DPAD_RIGHT
	GUIDE = JOY_GUIDE
	MISC1 = JOY_MISC1
	PADDLE1 = JOY_PADDLE1
	PADDLE2 = JOY_PADDLE2
	PADDLE3 = JOY_PADDLE3
	PADDLE4 = JOY_PADDLE4
	TOUCHPAD = JOY_TOUCHPAD
	L = JOY_L
	L2 = JOY_L2
	L3 = JOY_L3
	R = JOY_R
	R2 = JOY_R2
	R3 = JOY_R3
	VR_ANALOG_TRIGGER = JOY_VR_ANALOG_TRIGGER
	VR_ANALOG_GRIP = JOY_VR_ANALOG_GRIP
	OPENVR_TOUCHPADX = JOY_OPENVR_TOUCHPADX
	OPENVR_TOUCHPADY = JOY_OPENVR_TOUCHPADY
}

enum JoyAxes {
	LX = JOY_ANALOG_LX
	LY = JOY_ANALOG_LY
	RX = JOY_ANALOG_RX
	RY = JOY_ANALOG_RY
	L2 = JOY_ANALOG_L2
	R2 = JOY_ANALOG_R2
}

enum ButtonList {
	LEFT = BUTTON_LEFT
	RIGHT = BUTTON_RIGHT
	MIDDLE = BUTTON_MIDDLE
	XBUTTON1 = BUTTON_XBUTTON1
	XBUTTON2 = BUTTON_XBUTTON2
	WHEEL_UP = BUTTON_WHEEL_UP
	WHEEL_DOWN = BUTTON_WHEEL_DOWN
	WHEEL_LEFT = BUTTON_WHEEL_LEFT
	WHEEL_RIGHT = BUTTON_WHEEL_RIGHT
}
